version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: contract_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: contract_db
    ports:
      - "5434:5432"
    volumes:
      - contract_db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  contract_db_data:

